language: python
sudo: required
dist: trusty
git:
  depth: 5
env:
  - LEGACY=true
  - LEGACY=false
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis_retry travis/install_pandoc.sh
- travis_retry travis/install_liknorm.sh
script:
- travis_retry travis/test.sh
notifications:
  email: false
