language: python
sudo: required
dist: trusty
git:
  depth: 5
env:
  - LEGACY=true
  - LEGACY=false
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis_retry travis/install_pandoc.sh
- travis_retry travis/install_liknorm.sh
script:
- python setup.py sdist
- 'if [ ${LEGACY} = "true" ]; then
       travis_retry pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`[legacy] -vvv;
   else
       travis_retry pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1` -vvv;
   fi'
- pushd /
- python -c "import sys; import limix; sys.exit(limix.test())"
- popd
notifications:
  email: false
