language: python
sudo: required
dist: trusty
git:
  depth: 5
cache: pip
env:
  global:
  - PKG_NAME=limix
  - NUMBA=true
  - PY_DEPS="numpy scipy scikit-learn pandas h5py tables matplotlib limix-legacy limix-core
    sphinx_rtd_theme numba"
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
- travis_retry travis/test-before-install.sh
script:
- pip install pep8 --upgrade -q
- find limix -name \*.py -exec pep8 --ignore=E402 --ignore=E501 {} +
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email:
    recipients:
    - casale@ebi.ac.uk
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: Q27fcA59x0uSaSnMKt5TGIpO5WfIxJoOR62OmgwRxl9oFfVDJdzbbpAdouFYzxmSmXpnl/YotmbXSb2k8vB/3Dfiqz2e5K8Y9kWuZDOFAA+kVBuQB9RgaKR0oFJGgCwhhYkkvT5Vji1jYJqaUC2uEEz3swCrm/5/HidOo+2Zyp1S/ToTRNWPUHXRah1ohElkx/Hov2p3cEGadSuVUHkHvbsucxBvsZqDPRSdHkee9AtIpdCzQ2YAezva4mdj64ozrMyHNcuy5ooaFEY7BIMCTuKd2PmbimI+APFb3eZFTMiw9AZiY7wgLBNT7lqB6+0+aW+Q8kxDP9Xh7O2bPYUP83wLRDkq99f1CQcYhgevDseSNMS83wpg3DWOJtOfsfnU9bB3eg8YsCwaHSby5JXtub2rR9uY1gkZsLcmtsuhAUn2tavQ/7R0zC1/Jo6WPH6pI6koE/wjsZMSrs4/RqpQuGIqa2OYEBKFyxSb08gvWj+RFm0Shm/pVuM+YnlnuYVLd+0yCt87kPZgtnkgZSQieEU0A+BX600JOZOtIncB8UuQht+ifU5InLiqMkpNMaD5XtBwVKPyUnAc0PfwXExb/uuPMXYfIDcLkBxMhBXxJcNW8O2uwlhkMPHsRLl5LZpH7EmZqxj57qhCEhEBzhvTOHepHvwVSqZa+Bkv6H1YM9I=
  on:
    tags: true
    repo: limix/limix
  branches:
    only:
    - master
