language: python
sudo: required
dist: trusty
git:
  depth: 5
env:
  global:
    - PKG_NAME=limix
    - PY_DEPS="numpy scipy scikit-learn pandas h5py tables matplotlib limix-legacy limix-core"
python:
- 2.7
- 3.5
- 3.6
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
- travis_retry travis/test-before-install.sh
script:
- pip install pep8 --upgrade -q
- find limix -name \*.py -exec pep8 --ignore=E402 --ignore=E501 {} +
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email:
    recipients:
      - casale@ebi.ac.uk
    on_failure: always
