language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
before_install:
- pip install Cython
- travis/install_pandoc.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1` -vvv;
- pushd /
- python -c "import sys; import limix_inference; sys.exit(limix_inference.test())"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: WwkdrB+XYEff98YpEQzRi4ganL1miLXoo8b1GSAF4n+4BNA7gEexHVmw3ZSZVonOwII+8Xl1iRydLcmiMlsWTTOUo1caOJRpaZFQjmgH4Up87oDaCrZ3EY68X/VG6RItRmxbxgGPbhGqVYpESl+HRuXhiTFM+JDYOZA1T3kZD9Gi/JAgpBAcLTqDSPg4iK3h4IAd9M07X9MTxbp+1/pbRvx96v9JJ2pbBNUxUFQjdp+OxTGIRCYAjzGeNsrl+XGgoDtwVBj/BfRSFy7qewGW1TA4i+J6x2Vey4jecKpR811RU5D7uivbtLIYg9OrD19M6szx69sjL6f3lW0tygYPTIgFHpBQDuiZveVh+T1RWg6bnsBTIDpwisqoATnYBxFiqOJlkABnw2kCcDEQ+cxseTYz/ldr71T41KwYI33mEbkZqz0W9h+5CQrbXJ7hFMunIsM7H4OFK1Hht3dYdhTHV2sJ6iEikzdsJWfoT8SvgP9lkRhaqmg9V4R/JK2kfY9n41iFenVZYm8Pl4YffaY1hlalukulCTXKRWDyGI3WY3Z4yCZS2GhVTMcv9Uc6bXhMqaHJ86igka2Jy+5h+DTCWohEtfDgmobWeKvZc5LKabwlqjsDuUk9L4X97ni0An8zedWXGTVkhw3K62n7zKTPcSsW30hJKW0ftMWRGUqorZA=
  on:
    repo: PMBio/limix
