language: python
sudo: required
dist: trusty
services: docker
git:
  depth: 5
cache:
  pip: true
  directories:
  - "$HOME/bin"
  - "$HOME/.download"
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    language: generic
    env: PYENV=py27
  - os: osx
    language: generic
    env: PYENV=py35
  - os: osx
    language: generic
    env: PYENV=py36
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
script:
- pip install pep8 --upgrade -q
- find limix -name \*.py -exec pep8 --ignore=E402 --ignore=E501 {} +
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email: false
env:
  global:
  - PKG_NAME=limix
  - LIKNORM=true
  - PY_DEPS="numpy scipy scikit-learn pandas h5py tables matplotlib
             limix-legacy limix-core sphinx_rtd_theme ncephes ndarray-listener
             brent-search"
  - secure: TGjO9nGH88bYMoRG3nBKYZn1Xj43/DzBK6lqWAL+2D7rd6jryPTSMy9R0luuqOUubhPCI7BpQVLKYXsRi0T0EGeRm4WbjQa2AD9TZlrvgRSWftMZ0U5UEvAoONMAsXV3CpND6Ey5yynRALjvt/4kH4a1IjIOwvSepxIwN7bGEFIXGyFq/scl65DT/7TFsv7UKzIKaOO6U9dq0vFekciCX+uuNF5pX7A8SMFrO6ydRfUtO47o9M+ieoGHgkQw0KyjD8wjbMa/2TXvpY6tAf8BnyYH8XhqJ7Tztzzc9Hbpxqr8b4LjnGr3UEfz6c0benzLufYwoQyi6T6T4ur1H19i0OS9LO/v9HrWkhuzx/15HH5b2GEZJK8DcnoWc/1csX5W9M3TbWhOIiCW8fyujVwcOznah7GW9cwPFuWP7+JZiw5E2B+u8ukkio9QsG7BV4+YJZCBevOGe70QNiEwUhF9E9TRyCXuQvORYv8nKIMoQ8GnujSEoHLmYMbdYEM/bLcOVfsfDOEWJPUvtBJ+Mmhz1DyMcS4qpUtStSu5Io38l1ZD7AdZ8iGGPkeYfF7ke4ZWQgx9CGrXVgYmyj016p0Z0mXr7GSDkhyIo4nhHb2EoH1rdW29T+GbSyz4Q9AtZNghkvZbYeFyvqsoWqXLn27dG91t7CZ7hT25gSag49VTbnA=
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: NS5ir5qJr4f9FcwVwJhNt8WIwOxDHyV4UJ6e01sZ2hPtW/afukFuCTgJ4duFJuYHWFlgMk1Kv3pEhQnTKwzi4MO7fqV7N0hg7e6L42OOL3BB0XamCtBnMY+76hPnXTSkGhA3wDrqBQ/dzBstN739qNPh3IeC8oax7otKh8QzyZfmIQHYqXQJqdTx6Cdap/gR4CF56h+VuNs7aGSRuvjVWV9lIOHsK/ZCKIE1QTq7aRnOAUU6fXtdE4uEqwOl4bzU1HauxElonSudaYiv+NTLNkB7YRR4Ur1VTa7HXNhs9y/RYId0R6xputp+ousutQg5mlGD/z2Qaez6hlwoCgAqIsVNeiLnNQinXx1Z+lJSLQfnw2AX5zi9HgAsgb6ts6gJm2vTCVuOBpcti0uJd9l+0LR0IuGLYwWz1lXQN7/hsAeQFpK/A4tzlDMGQV0wxNFvCq/hSe7LnVehnTOVmJ+HU51XAqF766HYyf+/KcKhaY8IDlpkuLxmTAvY5/vk/JPhmt8JtDP6q+afwSOiM47ciClRtXkRv4zrL/D8euDC1TtLb5Kqxwo59e7cPGB/kLaA9904i0FOcoclv0NZGxdRgXPNYS9ULofjGHzn0Cn5H4FVcYTS3YDYv6bSeNcodQ83zD4FBGvZLe1vuhRdwRbOWKcgeUJNeN0PTL7Txo7YchE=
  on:
    tags: true
    repo: limix/limix
    branch: master
